name: Test Dizipal CLI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if Node.js is installed and install if missing
        id: check_node
        run: |
          if ! command -v node &> /dev/null; then
            echo "Node.js is not installed. Installing..."
            # Install Node.js using setup-node action
            echo "node-version: '20'" >> $GITHUB_ENV
            echo "Using actions/setup-node to install Node.js 20.x"
            actions/setup-node@v3
          else
            echo "Node.js is already installed"
            node --version
          fi

      - name: Install Dizipal CLI
        run: npm install -g dizipal-cli

      - name: Run Dizipal CLI
        run: dizipal find --latest

      - name: Check if DIZIPAL environment variable is set
        id: check_env
        run: |
          if [ -z "$DIZIPAL" ]; then
            echo "DIZIPAL environment variable is not set. Skipping JSON modification."
            exit 0
          else
            echo "DIZIPAL environment variable is set to: $DIZIPAL"
            echo "DIZIPAL=$DIZIPAL" >> $GITHUB_ENV
          fi

      - name: Modify JSON file
        if: steps.check_env.outputs.DIZIPAL != ''
        run: |
          jq --arg value "$DIZIPAL" '.currentSiteURL = $value' test-api.json > temp.json
          mv temp.json test-api.json

      - name: Verify JSON content
        if: steps.check_env.outputs.DIZIPAL != ''
        run: cat test-api.json