name: Test Dizipal CLI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dizipal CLI
        run: npm install -g dizipal-cli

      - name: Run Dizipal CLI with custom API
        run: dizipal find --url https://dizipal738.com --api dizipal.json

      - name: Check if DIZIPAL environment variable is set
        run: |
          if [ -z "$DIZIPAL" ]; then
            echo "DIZIPAL environment variable is not set. Skipping JSON modification."
            exit 0
          else
            echo "DIZIPAL environment variable is set to: $DIZIPAL"
            echo "DIZIPAL=$DIZIPAL" >> $GITHUB_ENV
          fi

      - name: Modify JSON file
        if: env.DIZIPAL != ''
        run: |
          jq --arg value "$DIZIPAL" '.currentSiteURL = $value' test-api.json > temp.json
          mv temp.json test-api.json

      - name: Verify JSON content
        if: env.DIZIPAL != ''
        run: cat test-api.json